### ISSUE TITLE
Error: ENOENT: no such file or directory when create a mnemonic for Scope: 0

### ISSUE THREAD

**Issue by sangheestyle** [LoremLabs/kudos#29]
```
% npx @loremlabs/setler@latest pool get PSVWeCMhTfLkJ74r3k2K1L
✔ Setler Password:  … ****
✔ Would you like to create a mnemonic for Scope: 0? … yes
Error: ENOENT: no such file or directory, open '/Users/sanghee/Library/Application Support/setler/state/setlr-0.seed'
    at Object.openSync (node:fs:601:3)
    at Object.writeFileSync (node:fs:2249:35)
    at createSeed (file:///Users/sanghee/.npm/_npx/3fd0890560959e83/node_modules/@loremlabs/setler/src/lib/wallet/gatekeep.js:241:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async checkConfig (file:///Users/sanghee/.npm/_npx/3fd0890560959e83/node_modules/@loremlabs/setler/src/lib/wallet/gatekeep.js:268:18)
    at async gatekeep (file:///Users/sanghee/.npm/_npx/3fd0890560959e83/node_modules/@loremlabs/setler/src/lib/wallet/gatekeep.js:277:7)
    at async Module.exec (file:///Users/sanghee/.npm/_npx/3fd0890560959e83/node_modules/@loremlabs/setler/src/actions/pool.js:49:7)
% node --version                                    (issue/node16-compatibility)kudos
v18.16.1
%       
```

Tested on node 16, 18 and got errors.

**Comment by sangheestyle** [comment]
Fixed.
